/**
 * generated by Xtext 2.25.0
 */
package org.xtext.agen.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.agen.AgenPackage;
import org.xtext.agen.BigPacketFault;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Big Packet Fault</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.agen.impl.BigPacketFaultImpl#getOriginalData <em>Original Data</em>}</li>
 *   <li>{@link org.xtext.agen.impl.BigPacketFaultImpl#getTimesLarger <em>Times Larger</em>}</li>
 * </ul>
 *
 * @generated
 */
public class BigPacketFaultImpl extends MinimalEObjectImpl.Container implements BigPacketFault
{
  /**
   * The default value of the '{@link #getOriginalData() <em>Original Data</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOriginalData()
   * @generated
   * @ordered
   */
  protected static final int ORIGINAL_DATA_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getOriginalData() <em>Original Data</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOriginalData()
   * @generated
   * @ordered
   */
  protected int originalData = ORIGINAL_DATA_EDEFAULT;

  /**
   * The default value of the '{@link #getTimesLarger() <em>Times Larger</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTimesLarger()
   * @generated
   * @ordered
   */
  protected static final int TIMES_LARGER_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getTimesLarger() <em>Times Larger</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTimesLarger()
   * @generated
   * @ordered
   */
  protected int timesLarger = TIMES_LARGER_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BigPacketFaultImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AgenPackage.Literals.BIG_PACKET_FAULT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getOriginalData()
  {
    return originalData;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOriginalData(int newOriginalData)
  {
    int oldOriginalData = originalData;
    originalData = newOriginalData;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AgenPackage.BIG_PACKET_FAULT__ORIGINAL_DATA, oldOriginalData, originalData));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getTimesLarger()
  {
    return timesLarger;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTimesLarger(int newTimesLarger)
  {
    int oldTimesLarger = timesLarger;
    timesLarger = newTimesLarger;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AgenPackage.BIG_PACKET_FAULT__TIMES_LARGER, oldTimesLarger, timesLarger));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AgenPackage.BIG_PACKET_FAULT__ORIGINAL_DATA:
        return getOriginalData();
      case AgenPackage.BIG_PACKET_FAULT__TIMES_LARGER:
        return getTimesLarger();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AgenPackage.BIG_PACKET_FAULT__ORIGINAL_DATA:
        setOriginalData((Integer)newValue);
        return;
      case AgenPackage.BIG_PACKET_FAULT__TIMES_LARGER:
        setTimesLarger((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AgenPackage.BIG_PACKET_FAULT__ORIGINAL_DATA:
        setOriginalData(ORIGINAL_DATA_EDEFAULT);
        return;
      case AgenPackage.BIG_PACKET_FAULT__TIMES_LARGER:
        setTimesLarger(TIMES_LARGER_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AgenPackage.BIG_PACKET_FAULT__ORIGINAL_DATA:
        return originalData != ORIGINAL_DATA_EDEFAULT;
      case AgenPackage.BIG_PACKET_FAULT__TIMES_LARGER:
        return timesLarger != TIMES_LARGER_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (originalData: ");
    result.append(originalData);
    result.append(", timesLarger: ");
    result.append(timesLarger);
    result.append(')');
    return result.toString();
  }

} //BigPacketFaultImpl
