/**
 * generated by Xtext 2.25.0
 */
package org.xtext.agen;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.agen.AgenPackage
 * @generated
 */
public interface AgenFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AgenFactory eINSTANCE = org.xtext.agen.impl.AgenFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Types</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Types</em>'.
   * @generated
   */
  Types createTypes();

  /**
   * Returns a new object of class '<em>Run Configuration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Run Configuration</em>'.
   * @generated
   */
  RunConfiguration createRunConfiguration();

  /**
   * Returns a new object of class '<em>Node</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Node</em>'.
   * @generated
   */
  Node createNode();

  /**
   * Returns a new object of class '<em>Log</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Log</em>'.
   * @generated
   */
  Log createLog();

  /**
   * Returns a new object of class '<em>Syncpoint</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Syncpoint</em>'.
   * @generated
   */
  Syncpoint createSyncpoint();

  /**
   * Returns a new object of class '<em>Fault</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Fault</em>'.
   * @generated
   */
  Fault createFault();

  /**
   * Returns a new object of class '<em>Exec Params</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Exec Params</em>'.
   * @generated
   */
  ExecParams createExecParams();

  /**
   * Returns a new object of class '<em>What</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>What</em>'.
   * @generated
   */
  What createWhat();

  /**
   * Returns a new object of class '<em>Repeat Execution</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Repeat Execution</em>'.
   * @generated
   */
  RepeatExecution createRepeatExecution();

  /**
   * Returns a new object of class '<em>Alter Packet Fault</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Alter Packet Fault</em>'.
   * @generated
   */
  AlterPacketFault createAlterPacketFault();

  /**
   * Returns a new object of class '<em>Leak Fault</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Leak Fault</em>'.
   * @generated
   */
  LeakFault createLeakFault();

  /**
   * Returns a new object of class '<em>Big Packet Fault</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Big Packet Fault</em>'.
   * @generated
   */
  BigPacketFault createBigPacketFault();

  /**
   * Returns a new object of class '<em>Exit</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Exit</em>'.
   * @generated
   */
  Exit createExit();

  /**
   * Returns a new object of class '<em>Sleep</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sleep</em>'.
   * @generated
   */
  Sleep createSleep();

  /**
   * Returns a new object of class '<em>CPU Loader</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>CPU Loader</em>'.
   * @generated
   */
  CPULoader createCPULoader();

  /**
   * Returns a new object of class '<em>Code Block</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Code Block</em>'.
   * @generated
   */
  CodeBlock createCodeBlock();

  /**
   * Returns a new object of class '<em>Fault Cond</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Fault Cond</em>'.
   * @generated
   */
  FaultCond createFaultCond();

  /**
   * Returns a new object of class '<em>When</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>When</em>'.
   * @generated
   */
  When createWhen();

  /**
   * Returns a new object of class '<em>Random</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Random</em>'.
   * @generated
   */
  Random createRandom();

  /**
   * Returns a new object of class '<em>between Seconds</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>between Seconds</em>'.
   * @generated
   */
  betweenSeconds createbetweenSeconds();

  /**
   * Returns a new object of class '<em>between Rounds</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>between Rounds</em>'.
   * @generated
   */
  betweenRounds createbetweenRounds();

  /**
   * Returns a new object of class '<em>Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Condition</em>'.
   * @generated
   */
  Condition createCondition();

  /**
   * Returns a new object of class '<em>Where</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Where</em>'.
   * @generated
   */
  Where createWhere();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  AgenPackage getAgenPackage();

} //AgenFactory
