/**
 * generated by Xtext 2.25.0
 */
package org.xtext.agen;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.agen.Condition#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.agen.Condition#getImports <em>Imports</em>}</li>
 *   <li>{@link org.xtext.agen.Condition#getCode <em>Code</em>}</li>
 * </ul>
 *
 * @see org.xtext.agen.AgenPackage#getCondition()
 * @model
 * @generated
 */
public interface Condition extends Types
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.agen.AgenPackage#getCondition_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.agen.Condition#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Imports</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Imports</em>' attribute.
   * @see #setImports(String)
   * @see org.xtext.agen.AgenPackage#getCondition_Imports()
   * @model
   * @generated
   */
  String getImports();

  /**
   * Sets the value of the '{@link org.xtext.agen.Condition#getImports <em>Imports</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Imports</em>' attribute.
   * @see #getImports()
   * @generated
   */
  void setImports(String value);

  /**
   * Returns the value of the '<em><b>Code</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Code</em>' attribute.
   * @see #setCode(String)
   * @see org.xtext.agen.AgenPackage#getCondition_Code()
   * @model
   * @generated
   */
  String getCode();

  /**
   * Sets the value of the '{@link org.xtext.agen.Condition#getCode <em>Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Code</em>' attribute.
   * @see #getCode()
   * @generated
   */
  void setCode(String value);

} // Condition
