/**
 * generated by Xtext 2.25.0
 */
package org.xtext.agen;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fault</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.agen.Fault#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.agen.Fault#getPointcut <em>Pointcut</em>}</li>
 *   <li>{@link org.xtext.agen.Fault#getExecParams <em>Exec Params</em>}</li>
 * </ul>
 *
 * @see org.xtext.agen.AgenPackage#getFault()
 * @model
 * @generated
 */
public interface Fault extends Types
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.agen.AgenPackage#getFault_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.agen.Fault#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Pointcut</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pointcut</em>' attribute.
   * @see #setPointcut(String)
   * @see org.xtext.agen.AgenPackage#getFault_Pointcut()
   * @model
   * @generated
   */
  String getPointcut();

  /**
   * Sets the value of the '{@link org.xtext.agen.Fault#getPointcut <em>Pointcut</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pointcut</em>' attribute.
   * @see #getPointcut()
   * @generated
   */
  void setPointcut(String value);

  /**
   * Returns the value of the '<em><b>Exec Params</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.agen.ExecParams}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exec Params</em>' containment reference list.
   * @see org.xtext.agen.AgenPackage#getFault_ExecParams()
   * @model containment="true"
   * @generated
   */
  EList<ExecParams> getExecParams();

} // Fault
