/**
 * generated by Xtext 2.25.0
 */
package org.xtext.agen;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Leak Fault</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.agen.LeakFault#getNrofLeaks <em>Nrof Leaks</em>}</li>
 * </ul>
 *
 * @see org.xtext.agen.AgenPackage#getLeakFault()
 * @model
 * @generated
 */
public interface LeakFault extends EObject
{
  /**
   * Returns the value of the '<em><b>Nrof Leaks</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nrof Leaks</em>' attribute.
   * @see #setNrofLeaks(int)
   * @see org.xtext.agen.AgenPackage#getLeakFault_NrofLeaks()
   * @model
   * @generated
   */
  int getNrofLeaks();

  /**
   * Sets the value of the '{@link org.xtext.agen.LeakFault#getNrofLeaks <em>Nrof Leaks</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nrof Leaks</em>' attribute.
   * @see #getNrofLeaks()
   * @generated
   */
  void setNrofLeaks(int value);

} // LeakFault
