/**
 * generated by Xtext 2.25.0
 */
package org.xtext.agen;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Log</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.agen.Log#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.agen.Log#getFaultCond <em>Fault Cond</em>}</li>
 *   <li>{@link org.xtext.agen.Log#getExtraData <em>Extra Data</em>}</li>
 *   <li>{@link org.xtext.agen.Log#getStateBased <em>State Based</em>}</li>
 * </ul>
 *
 * @see org.xtext.agen.AgenPackage#getLog()
 * @model
 * @generated
 */
public interface Log extends Types
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.agen.AgenPackage#getLog_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.agen.Log#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Fault Cond</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fault Cond</em>' attribute.
   * @see #setFaultCond(String)
   * @see org.xtext.agen.AgenPackage#getLog_FaultCond()
   * @model
   * @generated
   */
  String getFaultCond();

  /**
   * Sets the value of the '{@link org.xtext.agen.Log#getFaultCond <em>Fault Cond</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fault Cond</em>' attribute.
   * @see #getFaultCond()
   * @generated
   */
  void setFaultCond(String value);

  /**
   * Returns the value of the '<em><b>Extra Data</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Extra Data</em>' containment reference.
   * @see #setExtraData(CodeBlock)
   * @see org.xtext.agen.AgenPackage#getLog_ExtraData()
   * @model containment="true"
   * @generated
   */
  CodeBlock getExtraData();

  /**
   * Sets the value of the '{@link org.xtext.agen.Log#getExtraData <em>Extra Data</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Extra Data</em>' containment reference.
   * @see #getExtraData()
   * @generated
   */
  void setExtraData(CodeBlock value);

  /**
   * Returns the value of the '<em><b>State Based</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>State Based</em>' containment reference.
   * @see #setStateBased(CodeBlock)
   * @see org.xtext.agen.AgenPackage#getLog_StateBased()
   * @model containment="true"
   * @generated
   */
  CodeBlock getStateBased();

  /**
   * Sets the value of the '{@link org.xtext.agen.Log#getStateBased <em>State Based</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>State Based</em>' containment reference.
   * @see #getStateBased()
   * @generated
   */
  void setStateBased(CodeBlock value);

} // Log
