/**
 * generated by Xtext 2.25.0
 */
package org.xtext.agen;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Node</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.agen.Node#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.agen.Node#getFirstAttachPoint <em>First Attach Point</em>}</li>
 *   <li>{@link org.xtext.agen.Node#getNodeLocation <em>Node Location</em>}</li>
 *   <li>{@link org.xtext.agen.Node#getLogLocations <em>Log Locations</em>}</li>
 *   <li>{@link org.xtext.agen.Node#getFaultIDs <em>Fault IDs</em>}</li>
 * </ul>
 *
 * @see org.xtext.agen.AgenPackage#getNode()
 * @model
 * @generated
 */
public interface Node extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.agen.AgenPackage#getNode_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.agen.Node#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>First Attach Point</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>First Attach Point</em>' attribute.
   * @see #setFirstAttachPoint(String)
   * @see org.xtext.agen.AgenPackage#getNode_FirstAttachPoint()
   * @model
   * @generated
   */
  String getFirstAttachPoint();

  /**
   * Sets the value of the '{@link org.xtext.agen.Node#getFirstAttachPoint <em>First Attach Point</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>First Attach Point</em>' attribute.
   * @see #getFirstAttachPoint()
   * @generated
   */
  void setFirstAttachPoint(String value);

  /**
   * Returns the value of the '<em><b>Node Location</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Node Location</em>' attribute.
   * @see #setNodeLocation(String)
   * @see org.xtext.agen.AgenPackage#getNode_NodeLocation()
   * @model
   * @generated
   */
  String getNodeLocation();

  /**
   * Sets the value of the '{@link org.xtext.agen.Node#getNodeLocation <em>Node Location</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Node Location</em>' attribute.
   * @see #getNodeLocation()
   * @generated
   */
  void setNodeLocation(String value);

  /**
   * Returns the value of the '<em><b>Log Locations</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Log Locations</em>' attribute list.
   * @see org.xtext.agen.AgenPackage#getNode_LogLocations()
   * @model unique="false"
   * @generated
   */
  EList<String> getLogLocations();

  /**
   * Returns the value of the '<em><b>Fault IDs</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fault IDs</em>' attribute list.
   * @see org.xtext.agen.AgenPackage#getNode_FaultIDs()
   * @model unique="false"
   * @generated
   */
  EList<String> getFaultIDs();

} // Node
