/**
 * generated by Xtext 2.25.0
 */
package org.xtext.agen;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Repeat Execution</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.agen.RepeatExecution#getTimes <em>Times</em>}</li>
 * </ul>
 *
 * @see org.xtext.agen.AgenPackage#getRepeatExecution()
 * @model
 * @generated
 */
public interface RepeatExecution extends EObject
{
  /**
   * Returns the value of the '<em><b>Times</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Times</em>' attribute.
   * @see #setTimes(int)
   * @see org.xtext.agen.AgenPackage#getRepeatExecution_Times()
   * @model
   * @generated
   */
  int getTimes();

  /**
   * Sets the value of the '{@link org.xtext.agen.RepeatExecution#getTimes <em>Times</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Times</em>' attribute.
   * @see #getTimes()
   * @generated
   */
  void setTimes(int value);

} // RepeatExecution
