/**
 * generated by Xtext 2.25.0
 */
package org.xtext.agen;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Syncpoint</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.agen.Syncpoint#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.agen.Syncpoint#getNodesDependant <em>Nodes Dependant</em>}</li>
 *   <li>{@link org.xtext.agen.Syncpoint#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.agen.Syncpoint#getOnFail <em>On Fail</em>}</li>
 *   <li>{@link org.xtext.agen.Syncpoint#getFaultCond <em>Fault Cond</em>}</li>
 * </ul>
 *
 * @see org.xtext.agen.AgenPackage#getSyncpoint()
 * @model
 * @generated
 */
public interface Syncpoint extends Types
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.agen.AgenPackage#getSyncpoint_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.agen.Syncpoint#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Nodes Dependant</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nodes Dependant</em>' attribute list.
   * @see org.xtext.agen.AgenPackage#getSyncpoint_NodesDependant()
   * @model unique="false"
   * @generated
   */
  EList<String> getNodesDependant();

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.agen.syncpointType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see org.xtext.agen.syncpointType
   * @see #setType(syncpointType)
   * @see org.xtext.agen.AgenPackage#getSyncpoint_Type()
   * @model
   * @generated
   */
  syncpointType getType();

  /**
   * Sets the value of the '{@link org.xtext.agen.Syncpoint#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see org.xtext.agen.syncpointType
   * @see #getType()
   * @generated
   */
  void setType(syncpointType value);

  /**
   * Returns the value of the '<em><b>On Fail</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.agen.syncpointOnFail}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>On Fail</em>' attribute.
   * @see org.xtext.agen.syncpointOnFail
   * @see #setOnFail(syncpointOnFail)
   * @see org.xtext.agen.AgenPackage#getSyncpoint_OnFail()
   * @model
   * @generated
   */
  syncpointOnFail getOnFail();

  /**
   * Sets the value of the '{@link org.xtext.agen.Syncpoint#getOnFail <em>On Fail</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>On Fail</em>' attribute.
   * @see org.xtext.agen.syncpointOnFail
   * @see #getOnFail()
   * @generated
   */
  void setOnFail(syncpointOnFail value);

  /**
   * Returns the value of the '<em><b>Fault Cond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fault Cond</em>' containment reference.
   * @see #setFaultCond(FaultCond)
   * @see org.xtext.agen.AgenPackage#getSyncpoint_FaultCond()
   * @model containment="true"
   * @generated
   */
  FaultCond getFaultCond();

  /**
   * Sets the value of the '{@link org.xtext.agen.Syncpoint#getFaultCond <em>Fault Cond</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fault Cond</em>' containment reference.
   * @see #getFaultCond()
   * @generated
   */
  void setFaultCond(FaultCond value);

} // Syncpoint
