/**
 * generated by Xtext 2.25.0
 */
package org.xtext.agen;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Where</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.agen.Where#getJoinType <em>Join Type</em>}</li>
 *   <li>{@link org.xtext.agen.Where#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see org.xtext.agen.AgenPackage#getWhere()
 * @model
 * @generated
 */
public interface Where extends Types
{
  /**
   * Returns the value of the '<em><b>Join Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.agen.JOIN_TYPE}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Join Type</em>' attribute.
   * @see org.xtext.agen.JOIN_TYPE
   * @see #setJoinType(JOIN_TYPE)
   * @see org.xtext.agen.AgenPackage#getWhere_JoinType()
   * @model
   * @generated
   */
  JOIN_TYPE getJoinType();

  /**
   * Sets the value of the '{@link org.xtext.agen.Where#getJoinType <em>Join Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Join Type</em>' attribute.
   * @see org.xtext.agen.JOIN_TYPE
   * @see #getJoinType()
   * @generated
   */
  void setJoinType(JOIN_TYPE value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.agen.AgenPackage#getWhere_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.agen.Where#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // Where
