/*
 * generated by Xtext 2.25.0
 */
package org.xtext.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.services.AgenGrammarAccess;

@SuppressWarnings("all")
public class AgenSyntacticSequencer extends AbstractSyntacticSequencer {

	protected AgenGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Node___SemicolonKeyword_10_0_LogDataKeyword_10_1_EqualsSignKeyword_10_2__q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (AgenGrammarAccess) access;
		match_Node___SemicolonKeyword_10_0_LogDataKeyword_10_1_EqualsSignKeyword_10_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getNodeAccess().getSemicolonKeyword_10_0()), new TokenAlias(false, false, grammarAccess.getNodeAccess().getLogDataKeyword_10_1()), new TokenAlias(false, false, grammarAccess.getNodeAccess().getEqualsSignKeyword_10_2()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Node___SemicolonKeyword_10_0_LogDataKeyword_10_1_EqualsSignKeyword_10_2__q.equals(syntax))
				emit_Node___SemicolonKeyword_10_0_LogDataKeyword_10_1_EqualsSignKeyword_10_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     (';' 'logData' '=')?
	 *
	 * This ambiguous syntax occurs at:
	 *     nodeLocation=STRING (ambiguity) ';' ')' (rule end)
	 *     nodeLocation=STRING (ambiguity) ';' faultIDs+=ID
	 */
	protected void emit_Node___SemicolonKeyword_10_0_LogDataKeyword_10_1_EqualsSignKeyword_10_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
