/*
 * generated by Xtext 2.24.0
 */
package org.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.AgenRuntimeModule;
import org.xtext.AgenStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class AgenIdeSetup extends AgenStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new AgenRuntimeModule(), new AgenIdeModule()));
	}
	
}
